apiVersion: v1
kind: Service
metadata:
  name: users-$BRANCH
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: users-$BRANCH
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-$BRANCH
spec:
  selector:
    matchLabels:
      app: users-$BRANCH
  replicas: 2
  template:
    metadata:
      labels:
        app: users-$BRANCH
    spec:
      containers:
      - name: users-$BRANCH
        image: sofusskovgaard/users-service:$COMMIT_SHA1
        ports:
        - containerPort: 8080